### ISSUE TITLE
maybe embed the html

### ISSUE THREAD

**Issue by mcqueenorama** [therealbill/redskull#35]
I saw your video, and am not sure i'll be diving into Redis at all yet, but this stuff caught my eye.  I thought I'd mention this one thing, since it would be nice to not require the html directory.  Jam it into the binary with one of these tools:  http://mattjibson.com/blog/2014/11/19/esc-embedding-static-assets/.  Its easy to do and would improve the setup procedure.

**Comment by therealbill** [comment]
I've considered it many times, but ultimately consider the tradeoff between deploying a directory which allows the user to customize the interface w/p compiling vs the single-binary-as-sole-asset approach. I may do it at some point but until the UI is fairly complete it makes more sense to me currently to leave it as a user-manageable asset.
