### ISSUE TITLE
unable to detect version control system for code

### ISSUE THREAD

**Issue by carterfields** [therealbill/redskull#40]
I'm no go programmer, just installing for this application, and my first time.
I'm getting a message:

go get github.com/therealbill/redskull
package code.google.com/p/go-uuid/uuid: unable to detect version control system for code.google.com/ path

My quick google search came back with the issue that code.google.com isn't around any more?  I searched Git and found the following: 

handlers/clone.go : ln 13
"code.google.com/p/go-uuid/uuid"

and later

~/work/src/github.com/therealbill/redskull# gpm install
sed: read error on stdin: Is a directory
>> Getting package 
package code.google.com/p/go-uuid/uuid: unable to detect version control system for code.google.com/ path
>> Setting  to version 
>> Building package 
handlers/clone.go:13:2: cannot find package "code.google.com/p/go-uuid/uuid" in any of:
	/usr/local/go/src/code.google.com/p/go-uuid/uuid (from $GOROOT)
	/root/work/src/code.google.com/p/go-uuid/uuid (from $GOPATH)

**Comment by therealbill** [comment]
Thanks for the heads up, I'll update this shortly. In the meantime you can comment out https://github.com/therealbill/redskull/blob/0d422503b76b7c887d1984d117a49d91af931984/handlers/clone.go#L61 and it should build fine.
